name: Github Rebot for Sealos test comment
on:
  issue_comment:
    types:
      - created
jobs:
  comment:
    if: startswith(github.event.comment.body, '/xx')
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.20.x
      - uses: actions/checkout@v3
      - name: Build file
        run: |
          make install
      - run: |
          gh-rebot action
        env:
          SEALOS_TYPE: "/comment"
          GH_TOKEN: "${{ secrets.GH_PAT }}"
